#define REFLECT_BND_X 
#define REFLECT_BND_Y 
#define REFLECT_BND_Z 
#define HYDRO_MESHLESS_FINITE_MASS 
#define EOS_GAMMA (5.0/3.0)
#define COOLING 
#define GRACKLE 
#define GRACKLE_CHEMISTRY 0
#define GRACKLE_OPTS 
#define NOGRAVITY 
#define ANALYTIC_GRAVITY 
#define GRADUAL_NO_AXISYMMETRIC_POTENTIAL 
#define HAVE_HDF5 
#define OUTPUT_ADDITIONAL_RUNINFO 
